# Generated by Django 4.0.5 on 2023-01-05 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0003_contact_alter_userprofile_firstname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='c_email',
            field=models.EmailField(max_length=100, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='c_message',
            field=models.TextField(verbose_name='Message'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='c_name',
            field=models.CharField(max_length=100, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='c_subject',
            field=models.CharField(max_length=100, verbose_name='Subject'),
        ),
    ]
