# Generated by Django 4.0.5 on 2023-01-05 02:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0004_s_registe_u_registe_alter_contact_c_email_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='s_registe',
        ),
    ]
